name: Build Mod

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Add build environment
      uses: Pathoschild/SMAPI-ModBuildWorkflow/add-build-environment@v1

    - name: Build mod
      run: dotnet build -c Release

    - name: Upload artifacts
      uses: Pathoschild/SMAPI-ModBuildWorkflow/upload-release-artifacts@v1
