name: Build Mod

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Add build environment
      uses: Pathoschild/SMAPI-ModBuildWorkflow/add-build-environment@v1

    - name: Build mod
      run: dotnet build -c Release

    - name: Package Mod Zip
      run: |
        mkdir -p ./Package/AndroidBackpackPaging
        cp bin/Release/net6.0/AndroidBackpackPaging.dll ./Package/AndroidBackpackPaging/
        cp manifest.json ./Package/AndroidBackpackPaging/
        cd Package && zip -r ../AndroidBackpackPaging.zip AndroidBackpackPaging

    - name: Upload Mod Zip
      uses: actions/upload-artifact@v4
      with:
        name: AndroidBackpackPaging-Mod
        path: AndroidBackpackPaging.zip
